format_version: 3
pipelines:
  spring-web-boot-support:
    lock_behavior: lockOnFailure
    group: SpringSupport
    materials:
      repo:
        git: https://github.com/pipo411/AG_SpringWebBootSupport-1.git
        branch: deploy-jenkins
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - clean
                      - assemble  

      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - check
              artifacts:
                - build:
                    source: build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: build/test-results/test/*.xml
                    destination: xml
                - build:
                    source: build/reports/jacoco/**/*
                    destination: coverage
                - build:
                    source: build/reports/findbugs/*.html
                    destination: bugs
                - build:
                    source: build/reports/pmd/*.html
                    destination: pmd     
              tabs:
                unit_test: xml/index.html
                htmlReports: html/index.html
                bugs_main: bugs/main.html
                bugs_test: bugs/test.html
                pmd_main: pmd/main.html
                pmd_test: pmd/test.html
                coverage: coverage/index.html
                
      - CodeQuality:
          jobs:
            CodeQuality:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - sonarqube 

      - Package:
          jobs:
            CapsuleJar:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - build
                      - capsule                  
              artifacts:
                - build:
                    source: build/libs/*.jar
                    destination: Capsule

       - Deploy:
          jobs:
            deploying: 
              tasks:
                - fetch:
                   stage: Package
                   job: CapsuleJar
                   source: Capsule/

                - exec:
                    command: ./gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.36
                      - -Puser_server=ubuntu
                      - -Pwar_path=Capsule
                      - -Puser_home=/home/go/llavedocker.pem
                                    
      
